name: Run All Tests
on:
  push:
    branches: [master]

jobs:
  Test-on-Chrome:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout GitCode
          uses: actions/checkout@v4.2.2

        - name: Install dependencies
          uses: cypress-io/github-action@v6.7.8
          with:
            runTests: false

        - name: Run Cypress Tests
          uses: cypress-io/github-action@v6.7.8
          with:
            record: true
            parallel: true
            command: "npm run cy:chrome:headless"
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        
        - name: Upload Videos to Build Artifacts
          uses: actions/upload-artifact@v3.1.2
          if: always()
          with:
            name: cypress-videos-chrome
            path: "${{ github.workspace }}/cypress/reports/videos/"
          
        - name: Upload Screenshots to Build Artifacts
          uses: actions/upload-artifact@v3.1.2
          if: failure()
          with:
            name: cypress-screenshots-chrome
            path: "${{ github.workspace }}/cypress/reports/screenshots/"
        
        - name: Upload Mocha report to Build Artifacts
          uses: actions/upload-artifact@v3.1.2
          if: always()
          with:
            name: cypress-mocha-chrome
            path: "${{ github.workspace }}/cypress/reports/html/"